# Site settings
title: Jacob Jamell 
email: jacob.jamell@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio thingy.  It's not very big right now,
  but I'm working to expand it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jjamell.github.io" # the base hostname & protocol for your site
twitter_username: kassick92 
github_username: jjamell 

# Build settings
markdown: kramdown
